import React from 'react'
import Header from '../../../components/Elements/Header'
import Pricing from '../../../components/Elements/Pricing'
import Image from 'next/image'
import TitleSection from '../../../components/Elements/TitleSection'
import EcosystemContent from '../../../components/PondsAndWaterfalls/Ecosystem/Content'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

const features = [
	'Fieldstone Boulders',
	'Riverstone',
	'EPDM Rubber Liner',
	'Heavy-Duty Underlayment',
	'Biological and Mechanical Filters',
	'LED Lighting',
	'Energy Efficient Pump',
	'Aerator',
	'Aquatic and Garden Berm Perennials',
	'Mulch',
	'Natural Wood Elements and Moss',
]

const ecoPonds = [
	{
		title: 'Homestay Pond Package',
		desc: 'A 7’ x 10’ Ecosystem Pond with 18" inch high waterfall',
		price: '14,995',
		img: '/pictures/ponds-and-waterfalls/ecosystem-ponds/homestay1.png',
	},
	{
		title: 'Destinations Pond Package',
		desc: 'A 10’ x 15’ Ecosystem Pond with a 6’ long cascading stream and falls',
		price: '19,995',
		img: '/pictures/ponds-and-waterfalls/ecosystem-ponds/destination1.jpeg',
	},
	{
		title: 'Staycation Pond Package',
		desc: 'A 20’ x 25’ Ecosystem Pond with a 10’ long cascading stream and falls',
		price: '34,495',
		img: '/pictures/ponds-and-waterfalls/ecosystem-ponds/staycation1.jpg',
	},
]
const EcosystemPonds = () => {
	return (
		<div className="relative z-10 min-h-screen bg-white">
			<Header
				title="Ponds and Waterfalls"
				desc="Start Planning Your Dream Pond"
			/>
			<TitleSection
				features={features}
				image="/pictures/ponds-and-waterfalls/ecosystem-ponds/ecosystem1.jpg"
				alt="Ecosystem Pond Title Picture"
			/>
			<div className="z-20 mx-auto flex max-w-7xl flex-col gap-6 py-16">
				{ecoPonds.map((pond, idx) => {
					return (
						<Pricing
							key={pond.title}
							corner={idx % 2 === 0 ? 'LEFT' : 'RIGHT'}
							price={pond.price}
							title={pond.title}
							desc={pond.desc}
							img={pond.img}
						/>
					)
				})}
			</div>
			<EcosystemContent />
		</div>
	)
}

export default EcosystemPonds