import React from 'react'
import Hero from '../components/Home/Hero'
import Services from '../components/Home/Services'
import Contact from '../components/Elements/Contact'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

const Home = () => {
	return (
		<>
			<Hero />
			<Services />
			<Contact />
		</>
	)
}

export default Home